### ISSUE TITLE
stacktraces don't show correctly with nim js

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#135]
* stacktraces in nim js don't format correctly  [EDIT: i thought it was a regression, but not sure anymore that it ever worked]

* --excessivestacktrace doesn't work with nim js (not sure whether it worked before)

### Example
```nim
# D20200426T190851
proc fun2()=doAssert false
proc fun1()=fun2()
fun1()
```

### Current Output
```
nim js -r --excessivestacktrace $timn_D/tests/nim/all/t10633.nim
Hint: 49103 LOC; 0.060 sec; 49.09MiB peakmem; Debug build; proj: /Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.nim; out: /Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js [SuccessX]
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:432
    throw new Error(cbuf_13465201);
    ^

Error: Error: unhandled exception: /Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.nim(5, 22) `false`  [AssertionError]
Traceback (most recent call last)
t10633.fun1, line: 6
t10633.fun2, line: 5
assertions.failedAssertImpl, line: 29
assertions.raiseAssert, line: 22
sysFatal.sysFatal, line: 49

    at unhandledException (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:432:11)
    at raiseException (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:265:5)
    at sysFatal_13377618 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:445:5)
    at raiseAssert_13377614 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:454:5)
    at failedAssertImpl_13377680 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:463:5)
    at fun2_13907003 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:473:5)
    at fun1_13915214 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:484:5)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js:489:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
Error: execution of an external program failed: '/usr/local/Cellar/node/13.12.0/bin/node /Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.js '
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp js <file>
```

### Expected Output
each entry in stacktrace (eg `t10633.fun2, line: 5`) should show full path, and formatted as usual as:
`/Users/timothee/git_clone/nim/timn/tests/nim/all/t10633.nim(5, 22)`

### Additional Information

* 9384f7ad35aa36a22b31d7541254e89890d6cec2

**Comment by metagn** [comment]
This is because compile options didn't work properly in JS, see https://github.com/nim-lang/Nim/issues/14153 which was fixed. [DefaultOptions - ChecksOptions - {optWarns}](https://github.com/nim-lang/Nim/blob/cc60caedb3a1c7043b0f7ef2db5c741ecaa1482f/compiler/options.nim#L333) were the active options at top level while DefaultOptions took over when a proc was instantiated.

**Comment by timotheecour** [comment]
I think this is a different issue; 
`nim c -r main shows`:
```
/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.nim(12) tscratch
/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.nim(11) fun1
/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.nim(10) fun2
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assertions.nim(29) failedAssertImpl
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assertions.nim(22) raiseAssert
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.nim(10, 22) `false`  [AssertionDefect]
```
(which is what I'm expecting for nim js as well), but nim js shows:
```
Error: Error: unhandled exception: /Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.nim(10, 22) `false`  [AssertionDefect]
Traceback (most recent call last)
module tscratch, line: 12
tscratch.fun1, line: 11
tscratch.fun2, line: 10
assertions.failedAssertImpl, line: 29
assertions.raiseAssert, line: 22
sysFatal.sysFatal, line: 49

    at unhandledException (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:437:11)
    at raiseException (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:264:5)
    at sysFatal_13317618 (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:450:5)
    at raiseAssert_13317614 (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:459:5)
    at failedAssertImpl_13317680 (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:468:5)
    at fun2_13857003 (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:478:5)
    at fun1_13865214 (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:489:5)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js:497:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
Error: execution of an external program failed: '/usr/local/Cellar/node/13.12.0/bin/node /Users/timothee/git_clone/nim/timn/src/timn/examples/tscratch.js '
```
the js stacktrace shows:
* a stacktrace pointing to nim sources => this one is broken for 2 reasons: no absolute paths despite `--excessivestacktrace`; and the formatting should be like `nim c` (`file(line) funname`)
* a stacktrace pointing to nim jsgen'd sources => this one is fine

**Comment by timotheecour** [comment]
fixed via https://github.com/nim-lang/Nim/pull/14230
